<?php

/**
 * @file
 * Contains ckeditor_plugin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cke_lightbox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cke_lightbox module.
    case 'help.page.cke_lightbox':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds lightbox plugin to CKEditor') . '</p>';
      return $output;

    default:
  }
}
